---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-data-pvdata
  labels:
    app: pgsql-data-pvdata
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/blockmap/pgsql_data
    server: 10.2.1.204
  # hostPath:
  #   path: "/Users/blockchain/pgsql_data"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: postgresql-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # namespace: pgsql-data
  name: postgresql-pv-claim
spec:
  volumeName: pgsql-data-pvdata
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: pgsql-data-pvdata

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: default
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: 12.3.1
data:
  config.json: |-
    {
      "server":"0.0.0.0",
      "server_port":9000,
      "password":"passcloud",
      "timeout":300,
      "method":"aes-256-cfb",
      "nameserver":"8.8.8.8",
      "mode":"tcp_and_udp"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: 12.3.1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/instance: 12.3.1
    spec:
      containers:
        - name: mysql
          image: docker.io/postgres:latest
          # image: docker.io/postgres:12.1
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              value: "pgsql@123"
          ports:
            - containerPort: 5432
              protocol: TCP
            # - containerPort: 1080
            #   protocol: TCP
          volumeMounts:
            # - name: postgresql-conf
            #   mountPath: /etc/mysql-libev
            # - name: postgresql-data
            #   mountPath: /var/lib/postgresql
            # - name: postgresql-persistent-storage
            #   mountPath: /var/lib/postgresql/data
      volumes:
        # - name: postgresql-conf
        #   configMap:
        #     name: postgresql-config
        # - name: postgresql-data
        #   hostPath:
        #     path: /opt/nginx/data_dir
        # - name: postgresql-persistent-storage
        #   persistentVolumeClaim:
        #     claimName: postgresql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: default
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: 12.3.1
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 32500
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: 12.3.1
