---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: default
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/instance: 3.0.0
data:
  config.json: |-
    {
      "server":"0.0.0.0",
      "server_port":9000,
      "password":"passcloud",
      "timeout":300,
      "method":"aes-256-cfb",
      "nameserver":"8.8.8.8",
      "mode":"tcp_and_udp"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: registry
      app.kubernetes.io/instance: 3.0.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: registry
        app.kubernetes.io/instance: 3.0.0
    spec:
      containers:
        - name: mysql
          image: docker.io/registry:latest
          # image: mohsenmottaghi/cloak-mysql:mysql-server
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_IP
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "9000"
            - name: ENCRYPTION
              value: "AES-256-CFB"
            - name: SERVER_PORT
              value: "password"
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 1080
              protocol: TCP
          volumeMounts:
            - name: registry-conf
              mountPath: /etc/mysql-libev
            - name: registry-data
              mountPath: /var/lib/registry
      volumes:
        - name: registry-conf
          configMap:
            name: registry-config
        - name: registry-data
          hostPath:
            path: /opt/nginx/data_dir

---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: default
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/instance: 3.0.0
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 32500
  selector:
    app.kubernetes.io/name: registry
    app.kubernetes.io/instance: 3.0.0
