---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoserver
  labels:
    app.kubernetes.io/name: geoserver
    app.kubernetes.io/instance: 2.16.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: geoserver
      app.kubernetes.io/instance: 2.16.2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: geoserver
        app.kubernetes.io/instance: 2.16.2
    spec:
      containers:
        - name: geoserver
          image: luoweb/geoserver:2.16.2
          imagePullPolicy: IfNotPresent
          env:
            - name: GEOSERVER_DATA_DIR
              value: /opt/geoserver/data_dir
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /geoserver/index.html
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /geoserver/index.html
              port: http
          volumeMounts:
            - name: geoserver-volume
              mountPath: "/opt/geoserver/data_dir"
      resources:
        limits:
          cpu: 2000m
          memory: 3000Mi
        requests:
          cpu: 1000m
          memory: 1024Mi
      volumes:
        # - name: geoserver-volume
        #   hostPath:
        #     path: /opt/geoserver/data_dir
        - name: geoserver-volume
          nfs:
            server: 10.2.1.204
            path: /data/geoserver/data_dir

---
apiVersion: v1
kind: Service
metadata:
  name: geoserver
  labels:
    app.kubernetes.io/name: geoserver
    app.kubernetes.io/instance: 2.16.2
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 32800
  selector:
    app.kubernetes.io/name: geoserver
    app.kubernetes.io/instance: 2.16.2
