apiVersion: v1
kind: Service
metadata:
  name: geoserver
  labels:
    app.kubernetes.io/name: geoserver
    app.kubernetes.io/instance: 2.16.2
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30657
  selector:
    app.kubernetes.io/name: geoserver
    app.kubernetes.io/instance: 2.16.2