---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blockmap-admin
  namespace: default
  labels:
    app.kubernetes.io/name: blockmap-admin
    app.kubernetes.io/instance: 0.0.1
data:
  default.conf: |-

    upstream geoserver {
        server 173.193.109.188:30657;
    }
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/blockmap/admin;
            index  index.html index.htm;
        }

        location /geoserver {
            proxy_pass http://geoserver;
            proxy_set_header   Host $host;
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET,POST,DELETE';
            add_header 'Access-Control-Allow-Header' 'Content-Type,*';
        }

        location /status {
            stub_status on;
            access_log off;
        }
        
        # redirect server error pages to the static page /50x.html
        # chengang from k8s config map file
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

    }
  nginx_passwd: |-
    admin:nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockmap-admin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blockmap-admin
      app.kubernetes.io/instance: 0.0.1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blockmap-admin
        app.kubernetes.io/instance: 0.0.1
    spec:
      containers:
        - name: blockmap
          image: luoweb/blockmap:all
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
            - mountPath: "/usr/share/nginx/html"
              name: blockmap-admin
      volumes:
        - name: nginx-conf
          configMap:
            name: blockmap-admin
        - name: blockmap-admin
          hostPath:
            path: /opt/nginx/data_dir
---
apiVersion: v1
kind: Service
metadata:
  name: blockmap-admin
  namespace: default
  labels:
    app.kubernetes.io/name: blockmap-admin
    app.kubernetes.io/instance: 0.0.1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32900
  selector:
    app.kubernetes.io/name: blockmap-admin
    app.kubernetes.io/instance: 0.0.1
