---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-static
  namespace: default
  labels:
    app.kubernetes.io/name: nginx-static
    app.kubernetes.io/instance: 1.17.9
data:
  default.conf: |-

    upstream geoserver {
        server 1.2.3.4:32766;
    }
    server {
        listen       80;
        server_name  localhost;


        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /check {
            default_type text/plain;
            return 200 "serving is ok!";
        }

        location /status {
            stub_status on;
            access_log off;
        }
        
        location  /nginx {
            proxy_pass http://nginx;
            proxy_set_header   Host $host;
        }
   
        # redirect server error pages to the static page /50x.html
        # chengang from k8s config map file
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

    }
  nginx_passwd: |-
    admin:nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-static
      app.kubernetes.io/instance: 1.17.9
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-static
        app.kubernetes.io/instance: 1.17.9
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - mountPath: "/usr/share/nginx/html"
          name: nginx-static
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-static
      - name: nginx-static
        hostPath:
          path: /opt/nginx/data_dir    
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-static
  namespace: default
  labels:
    app.kubernetes.io/name: nginx-static
    app.kubernetes.io/instance: 1.17.9
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32767
  selector:
    app.kubernetes.io/name: nginx-static
    app.kubernetes.io/instance: 1.17.9